apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
kind: Service
apiVersion: v1
metadata:
  name: grocy
  namespace: apps
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
spec:
  selector:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
  ports:
    - name: http
      port: 80
      targetPort: 80

---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: grocy-config
  namespace: apps
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  resources:
    requests:
      storage: "1Mi"

---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: grocy-data
  namespace: apps
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  resources:
    requests:
      storage: "1Gi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: apps
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
      app.kubernetes.io/instance: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
        app.kubernetes.io/instance: grocy
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/hostname: delacroix
      containers:
        - name: grocy
          imagePullPolicy: Always
          image: ghcr.io/linuxserver/grocy:arm64v8-version-v3.0.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: data
              mountPath: /var/www/data
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grocy-data
        - name: config
          persistentVolumeClaim:
            claimName: grocy-config
