# Source: elasticsearch/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: db
  name: es-cluster-master
  labels:
    app: elasticsearch
    release: elasticsearch
    heritage: Helm
spec:
  ingressClassName: "nginx"
  rules:
  - host: es.lan.repe.re
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: es-cluster-master
            port:
              number: 9200
