# Source: minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: s3
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
