apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: opencti
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: opencti-platform
  namespace: opencti
  labels:
    app.kubernetes.io/name: opencti-platform
    app.kubernetes.io/instance: opencti-platform
spec:
  selector:
    app.kubernetes.io/name: opencti-platform
  ports:
    - port: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: opencti
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
    - name: management
      port: 15672
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: opencti
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis
    spec:
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis:6.2.6
          resources:
            limits:
              memory: "256Mi"
          ports:
            - name: resp
              containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: opencti
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          imagePullPolicy: Always
          image: rabbitmq:3.9-management
          resources:
            limits:
              memory: "256Mi"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: opencti
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: rabbitmq
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencti-platform
  namespace: opencti
  labels:
    app.kubernetes.io/name: opencti-platform
    app.kubernetes.io/instance: opencti-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencti-platform
      app.kubernetes.io/instance: opencti-platform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencti-platform
        app.kubernetes.io/instance: opencti-platform
    spec:
      containers:
        - name: opencti-platform
          imagePullPolicy: Always
          image: opencti/platform:5.1.3
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=8096
            - name: APP__PORT
              value: "8080"
            - name: APP__ADMIN__EMAIL
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: email
            - name: APP__ADMIN__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: password
            - name: APP__ADMIN__TOKEN
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: token
            - name: APP__BASE_URL
              value: https://cti.lan.repe.re
            - name: APP__APP_LOGS__LOGS_LEVEL
              value: error
            - name: REDIS__HOSTNAME
              value: redis.opencti.svc.cluster.local
            - name: REDIS__PORT
              value: "6379"
            - name: REDIS__TRIMMING
              value: "1000"
            - name: ELASTICSEARCH__URL
              value: http://es-cluster-master.db.svc.cluster.local:9200
            - name: MINIO__ENDPOINT
              value: minio.db.svc.cluster.local
            - name: MINIO__PORT
              value: "9000"
            - name: MINIO__USE_SSL
              value: "false"
            - name: MINIO__ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: accesskey
            - name: MINIO__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secretkey
            - name: RABBITMQ__HOSTNAME
              value: rabbitmq.opencti.svc.cluster.local
            - name: RABBITMQ__PORT
              value: "5672"
            - name: RABBITMQ__PORT_MANAGEMENT
              value: "15672"
            - name: RABBITMQ__MANAGEMENT_SSL
              value: "false"
            - name: RABBITMQ__USERNAME
              value: opencti
            - name: RABBITMQ__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: rabbitmq
            - name: PROVIDERS__LOCAL__STRATEGY
              value: LocalStrategy
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: opencti
  name: opencti-worker
  labels:
    app.kubernetes.io/name: opencti-worker
    app.kubernetes.io/instance: opencti-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: opencti-worker
      app.kubernetes.io/instance: opencti-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencti-worker
        app.kubernetes.io/instance: opencti-worker
    spec:
      containers:
        - name: opencti-worker
          imagePullPolicy: Always
          image: opencti/worker:5.1.3
          resources:
            limits:
              memory: "2Gi"
          env:
            - name: OPENCTI_URL
              value: http://opencti-platform.opencti.svc.cluster.local:8080
            - name: WORKER_LOG_LEVEL
              value: info
            - name: OPENCTI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencti-export-file-stix
  namespace: opencti
  labels:
    app.kubernetes.io/name: opencti-export-file-stix
    app.kubernetes.io/instance: opencti-export-file-stix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencti-export-file-stix
      app.kubernetes.io/instance: opencti-export-file-stix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencti-export-file-stix
        app.kubernetes.io/instance: opencti-export-file-stix
    spec:
      containers:
        - name: opencti-export-file-stix
          imagePullPolicy: Always
          image:  opencti/connector-export-file-stix:5.1.3
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: 100Mi
              cpu: 10m
          env:
            - name: OPENCTI_URL
              value: http://opencti-platform.opencti.svc.cluster.local:8080
            - name: OPENCTI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: token
            - name: CONNECTOR_ID
              value: 1d6f0057-58d7-459c-b579-683d11ef30e2
            - name: CONNECTOR_TYPE
              value: INTERNAL_EXPORT_FILE
            - name: CONNECTOR_NAME
              value: ExportFileStix2
            - name: CONNECTOR_SCOPE
              value: application/json
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: "15"
            - name: CONNECTOR_LOG_LEVEL
              value: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencti-import-file-stix
  namespace: opencti
  labels:
    app.kubernetes.io/name: opencti-import-file-stix
    app.kubernetes.io/instance: opencti-import-file-stix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencti-import-file-stix
      app.kubernetes.io/instance: opencti-import-file-stix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencti-import-file-stix
        app.kubernetes.io/instance: opencti-import-file-stix
    spec:
      containers:
        - name: opencti-import-file-stix
          imagePullPolicy: Always
          image:  opencti/connector-export-file-stix:5.1.3
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: 100Mi
              cpu: 10m
          env:
            - name: OPENCTI_URL
              value: http://opencti-platform.opencti.svc.cluster.local:8080
            - name: OPENCTI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opencti
                  key: token
            - name: CONNECTOR_ID
              value: f6ba71d0-af4b-44c8-8c22-7419d7c31fbd
            - name: CONNECTOR_TYPE
              value: INTERNAL_IMPORT_FILE
            - name: CONNECTOR_NAME
              value: ImportFileStix
            - name: CONNECTOR_VALIDATE_BEFORE_IMPORT
              value: "true"
            - name: CONNECTOR_SCOPE
              value: application/json,text/xml
            - name: CONNECTOR_AUTO
              value: "true"
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: "15"
            - name: CONNECTOR_LOG_LEVEL
              value: info
